/**
 * Shared GitHub API utilities.
 *
 * All GitHub interactions live here so review.js and comment.js stay lean.
 *
 * Every public function that calls the GitHub API accepts an explicit `token`
 * parameter (either the user's personal OAuth token or the server fallback).
 * This enables per-user GitHub access without ever reading process.env inside
 * a request handler.
 */

const axios  = require('axios');
const logger = require('./logger');

const DEDUP_MARKER   = '## 🤖 AI Code Review';
const DEDUP_WINDOW   = 5 * 60 * 1000; // 5 minutes in ms
const SEVERITY_EMOJI = { high: '🔴', medium: '🟡', low: '🟢' };

// ─── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Parse a GitHub PR URL into { owner, repo, pull_number }.
 * Throws a descriptive Error on bad input.
 */
function parsePrUrl(url) {
  const match = (url || '').trim().match(/github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/);
  if (!match) {
    throw new Error(
      'Invalid GitHub PR URL. Expected: https://github.com/{owner}/{repo}/pull/{number}'
    );
  }
  return { owner: match[1], repo: match[2], pull_number: parseInt(match[3], 10) };
}

/**
 * Build GitHub API request headers.
 *
 * @param {string}      accept  - GitHub media type (default JSON)
 * @param {string|null} token   - GitHub access token (user or server)
 */
function ghHeaders(accept = 'application/vnd.github.v3+json', token = null) {
  const headers = {
    Accept:       accept,
    'User-Agent': 'AI-Code-Review-Tool/1.0',
  };
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }
  return headers;
}

// ─── Data fetching ─────────────────────────────────────────────────────────────

/**
 * Fetch PR metadata (JSON) and the unified diff in parallel.
 *
 * @param {string} owner
 * @param {string} repo
 * @param {number} pull_number
 * @param {string} token  — GitHub access token
 * @returns {{ prDetails: object, diff: string }}
 */
async function fetchPrData(owner, repo, pull_number, token) {
  const apiBase = `https://api.github.com/repos/${owner}/${repo}/pulls/${pull_number}`;

  const [metaRes, diffRes] = await Promise.all([
    axios.get(apiBase, {
      headers:  ghHeaders('application/vnd.github.v3+json', token),
      timeout:  15000,
    }),
    axios.get(apiBase, {
      headers:           ghHeaders('application/vnd.github.v3.diff', token),
      timeout:           15000,
      responseType:      'text',
      transformResponse: [(data) => data], // prevent axios from JSON-parsing a diff
    }),
  ]);

  return { prDetails: metaRes.data, diff: diffRes.data };
}

// ─── Duplicate detection ───────────────────────────────────────────────────────

/**
 * Returns true if an AI review comment was posted on this PR within
 * the last `windowMs` milliseconds.
 *
 * Silently returns false if the check itself fails (don't block the review).
 *
 * @param {string} owner
 * @param {string} repo
 * @param {number} pull_number
 * @param {string} token
 * @param {number} windowMs
 */
async function isDuplicateReview(owner, repo, pull_number, token, windowMs = DEDUP_WINDOW) {
  try {
    const res = await axios.get(
      `https://api.github.com/repos/${owner}/${repo}/issues/${pull_number}/comments`,
      {
        headers: ghHeaders('application/vnd.github.v3+json', token),
        params:  { per_page: 10, sort: 'created', direction: 'desc' },
        timeout: 10000,
      }
    );

    const cutoff = Date.now() - windowMs;
    for (const comment of res.data) {
      const createdAt = new Date(comment.created_at).getTime();
      if (createdAt < cutoff) break; // comments are newest-first; stop once past the window
      if (comment.body?.includes(DEDUP_MARKER)) return true;
    }
    return false;
  } catch (err) {
    logger.warn('github.dedup_check_failed', { owner, repo, pull_number, error: err.message });
    return false;
  }
}

// ─── Comment formatters ────────────────────────────────────────────────────────

/** Build the markdown body for the main PR comment. */
function buildGeneralComment(summary, confidence_score, issues, pr_title, triggered_by) {
  const lines = [];

  lines.push(DEDUP_MARKER); // marker used by dedup check — do not remove
  if (pr_title) lines.push(`> **PR:** ${pr_title}\n`);

  lines.push('### Summary');
  lines.push(summary || '_No summary provided._');
  lines.push('');

  if (confidence_score != null) {
    lines.push(`**Confidence score:** ${confidence_score}/100`);
    lines.push('');
  }

  if (triggered_by && triggered_by !== 'manual') {
    lines.push(`_Triggered by: \`${triggered_by}\`_`);
    lines.push('');
  }

  if (!issues?.length) {
    lines.push('✅ **No issues found — the PR looks good!**');
    lines.push('');
    lines.push('_Generated by [AI Code Review Dashboard](https://github.com)_');
    return lines.join('\n');
  }

  const counts = issues.reduce((acc, { severity }) => {
    const s = (severity || 'low').toLowerCase();
    acc[s] = (acc[s] || 0) + 1;
    return acc;
  }, {});

  const pills = [];
  if (counts.high)   pills.push(`🔴 ${counts.high} high`);
  if (counts.medium) pills.push(`🟡 ${counts.medium} medium`);
  if (counts.low)    pills.push(`🟢 ${counts.low} low`);
  lines.push(`**Issues found:** ${issues.length}  (${pills.join(' · ')})`);
  lines.push('');
  lines.push('### Issues');
  lines.push('');

  for (const issue of issues) {
    const sev   = (issue.severity || 'low').toLowerCase();
    const emoji = SEVERITY_EMOJI[sev] || '⚪';
    const fileRef =
      issue.file && issue.file !== 'general'
        ? issue.line != null
          ? `\`${issue.file}\` line ${issue.line}`
          : `\`${issue.file}\``
        : '_general_';

    lines.push(`#### ${emoji} ${issue.issue}`);
    lines.push(`**File:** ${fileRef}  |  **Severity:** ${sev}`);
    if (issue.suggestion) {
      lines.push('');
      lines.push(`> 💡 **Suggestion:** ${issue.suggestion}`);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push('_Generated by [AI Code Review Dashboard](https://github.com)_');
  return lines.join('\n');
}

/** Build the body for a single inline diff comment. */
function buildInlineComment(issue) {
  const sev   = (issue.severity || 'low').toLowerCase();
  const emoji = SEVERITY_EMOJI[sev] || '⚪';
  const lines = [`${emoji} **AI Review — ${sev} severity**`, '', issue.issue];
  if (issue.suggestion) {
    lines.push('');
    lines.push(`> 💡 **Suggestion:** ${issue.suggestion}`);
  }
  return lines.join('\n');
}

// ─── Comment posting ───────────────────────────────────────────────────────────

/**
 * Post the general review summary comment on the PR.
 * Throws on HTTP errors.
 *
 * @param {string} token  — GitHub access token
 */
async function postGeneralComment(owner, repo, pull_number, body, token) {
  const res = await axios.post(
    `https://api.github.com/repos/${owner}/${repo}/issues/${pull_number}/comments`,
    { body },
    { headers: ghHeaders('application/vnd.github.v3+json', token), timeout: 10000 }
  );
  return res.data.html_url;
}

/**
 * Attempt to post one inline diff comment. Returns true on success.
 * Returns false silently if the line is invalid (422).
 *
 * @param {string} token  — GitHub access token
 */
async function tryInlineComment(owner, repo, pull_number, commit_sha, issue, token) {
  if (!issue.file || issue.file === 'general' || !issue.line) return false;

  try {
    await axios.post(
      `https://api.github.com/repos/${owner}/${repo}/pulls/${pull_number}/comments`,
      {
        body:      buildInlineComment(issue),
        commit_id: commit_sha,
        path:      issue.file,
        line:      issue.line,
        side:      'RIGHT',
      },
      { headers: ghHeaders('application/vnd.github.v3+json', token), timeout: 10000 }
    );
    return true;
  } catch (err) {
    if (err.response?.status !== 422) {
      logger.warn('github.inline_comment_failed', {
        file:  issue.file,
        line:  issue.line,
        error: err.response?.data?.message || err.message,
      });
    }
    return false;
  }
}

/**
 * Post the full review (general + inline comments) to GitHub.
 * Returns a result object; never throws — caller decides how to handle failures.
 *
 * @param {object} opts
 * @param {string} opts.token  — GitHub access token
 */
async function postReviewToGitHub({
  owner, repo, pull_number, commit_sha, pr_title,
  summary, confidence_score, issues, triggered_by,
  token,
}) {
  const body = buildGeneralComment(summary, confidence_score, issues, pr_title, triggered_by);

  let generalCommentUrl;
  try {
    generalCommentUrl = await postGeneralComment(owner, repo, pull_number, body, token);
  } catch (err) {
    const status = err.response?.status;
    const hint =
      status === 401 ? ' — check GitHub token'
      : status === 403 ? ' — token may lack write access to this repo'
      : status === 404 ? ' — repo or PR not found'
      : '';
    throw new Error(
      `Failed to post GitHub comment${hint}: ${err.response?.data?.message || err.message}`
    );
  }

  // Inline comments — best effort; failures don't abort the response
  let inlinePosted = 0, inlineSkipped = 0;
  if (commit_sha && issues?.length) {
    for (const issue of issues) {
      const ok = await tryInlineComment(owner, repo, pull_number, commit_sha, issue, token);
      if (ok) inlinePosted++;
      else     inlineSkipped++;
    }
  } else {
    inlineSkipped = issues?.length || 0;
  }

  return {
    general_comment_url: generalCommentUrl,
    inline_posted:       inlinePosted,
    inline_skipped:      inlineSkipped,
  };
}

// ─── Exports ───────────────────────────────────────────────────────────────────

module.exports = {
  parsePrUrl,
  ghHeaders,
  fetchPrData,
  isDuplicateReview,
  buildGeneralComment,
  postReviewToGitHub,
  postGeneralComment,
  tryInlineComment,
};
